// <auto-generated />
using System;
using Aviscom.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aviscom.Migrations
{
    [DbContext(typeof(AviscomContext))]
    [Migration("20251115105641_CorrigirUsuarioFuncaoFK")]
    partial class CorrigirUsuarioFuncaoFK
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Aviscom.Models.Usuario.Contato", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)");

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("FkPessoaFisicaId")
                        .HasColumnType("char(26)");

                    b.Property<string>("FkPessoaJuridicaId")
                        .HasColumnType("char(26)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FkPessoaFisicaId");

                    b.HasIndex("FkPessoaJuridicaId");

                    b.ToTable("Contatos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Contatos_Usuario_Exclusivo", "[FkPessoaFisicaId] IS NULL OR [FkPessoaJuridicaId] IS NULL");
                        });
                });

            modelBuilder.Entity("Aviscom.Models.Usuario.Empresa", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)");

                    b.Property<string>("CNPJ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Empresas", (string)null);
                });

            modelBuilder.Entity("Aviscom.Models.Usuario.Endereco", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complemento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FkPessoaFisicaId")
                        .HasColumnType("char(26)");

                    b.Property<string>("FkPessoaJuridicaId")
                        .HasColumnType("char(26)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoLogradouro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FkPessoaFisicaId");

                    b.HasIndex("FkPessoaJuridicaId");

                    b.ToTable("Endereco", null, t =>
                        {
                            t.HasCheckConstraint("CK_Endereco_Usuario_Exclusivo", "[FkPessoaFisicaId] IS NULL OR [FkPessoaJuridicaId] IS NULL");
                        });
                });

            modelBuilder.Entity("Aviscom.Models.Usuario.Escolaridade", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)");

                    b.Property<int?>("AnoConclusao")
                        .HasColumnType("int");

                    b.Property<int?>("AnoInicio")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("FkInstituicaoId")
                        .IsRequired()
                        .HasColumnType("char(26)");

                    b.Property<string>("FkUsuarioId")
                        .IsRequired()
                        .HasColumnType("char(26)");

                    b.Property<string>("NomeCurso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FkInstituicaoId");

                    b.HasIndex("FkUsuarioId");

                    b.ToTable("Escolaridades", (string)null);
                });

            modelBuilder.Entity("Aviscom.Models.Usuario.ExperienciaProfissional", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)");

                    b.Property<int?>("AnoEntrada")
                        .HasColumnType("int");

                    b.Property<int?>("AnoSaida")
                        .HasColumnType("int");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DescricaoAtividades")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FkEmpresaId")
                        .IsRequired()
                        .HasColumnType("char(26)");

                    b.Property<string>("FkUsuarioId")
                        .IsRequired()
                        .HasColumnType("char(26)");

                    b.HasKey("Id");

                    b.HasIndex("FkEmpresaId");

                    b.HasIndex("FkUsuarioId");

                    b.ToTable("ExperienciasProfissionais", (string)null);
                });

            modelBuilder.Entity("Aviscom.Models.Usuario.Funcao", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)");

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Funcoes", (string)null);
                });

            modelBuilder.Entity("Aviscom.Models.Usuario.Instituicao", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)");

                    b.Property<string>("CNPJ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Instituicoes", (string)null);
                });

            modelBuilder.Entity("Aviscom.Models.Usuario.Setor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)");

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Setores", (string)null);
                });

            modelBuilder.Entity("Aviscom.Models.Usuario.UsuarioFuncao", b =>
                {
                    b.Property<string>("FkPessoaFisicaId")
                        .HasColumnType("char(26)");

                    b.Property<string>("FkPessoaJuridicaId")
                        .HasColumnType("char(26)");

                    b.Property<string>("FkFuncaoId")
                        .HasColumnType("char(26)");

                    b.Property<string>("FkSetorId")
                        .HasColumnType("char(26)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FkPessoaFisicaId", "FkPessoaJuridicaId", "FkFuncaoId", "FkSetorId");

                    b.HasIndex("FkFuncaoId");

                    b.HasIndex("FkPessoaJuridicaId");

                    b.HasIndex("FkSetorId");

                    b.ToTable("UsuariosFuncoes");
                });

            modelBuilder.Entity("Aviscom.Models.Usuario.UsuarioPessoaFisica", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)");

                    b.Property<string>("CpfCriptografado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CpfHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimoLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeMae")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomePai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeSocial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CpfHash")
                        .IsUnique();

                    b.ToTable("UsuariosFisicos", (string)null);
                });

            modelBuilder.Entity("Aviscom.Models.Usuario.UsuarioPessoaJuridica", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("CnpjHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DataUltimoLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("FkResponsavelId")
                        .IsRequired()
                        .HasColumnType("char(26)");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CnpjHash")
                        .IsUnique();

                    b.HasIndex("FkResponsavelId");

                    b.ToTable("UsuariosJuridicos", (string)null);
                });

            modelBuilder.Entity("Aviscom.Models.Usuario.Contato", b =>
                {
                    b.HasOne("Aviscom.Models.Usuario.UsuarioPessoaFisica", "PessoaFisica")
                        .WithMany("Contatos")
                        .HasForeignKey("FkPessoaFisicaId");

                    b.HasOne("Aviscom.Models.Usuario.UsuarioPessoaJuridica", "PessoaJuridica")
                        .WithMany("Contatos")
                        .HasForeignKey("FkPessoaJuridicaId");

                    b.Navigation("PessoaFisica");

                    b.Navigation("PessoaJuridica");
                });

            modelBuilder.Entity("Aviscom.Models.Usuario.Endereco", b =>
                {
                    b.HasOne("Aviscom.Models.Usuario.UsuarioPessoaFisica", "PessoaFisica")
                        .WithMany("Enderecos")
                        .HasForeignKey("FkPessoaFisicaId");

                    b.HasOne("Aviscom.Models.Usuario.UsuarioPessoaJuridica", "PessoaJuridica")
                        .WithMany("Enderecos")
                        .HasForeignKey("FkPessoaJuridicaId");

                    b.Navigation("PessoaFisica");

                    b.Navigation("PessoaJuridica");
                });

            modelBuilder.Entity("Aviscom.Models.Usuario.Escolaridade", b =>
                {
                    b.HasOne("Aviscom.Models.Usuario.Instituicao", "Instituicao")
                        .WithMany("EscolaridadesAssociadas")
                        .HasForeignKey("FkInstituicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aviscom.Models.Usuario.UsuarioPessoaFisica", "Usuario")
                        .WithMany("Escolaridades")
                        .HasForeignKey("FkUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instituicao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Aviscom.Models.Usuario.ExperienciaProfissional", b =>
                {
                    b.HasOne("Aviscom.Models.Usuario.Empresa", "Empresa")
                        .WithMany("Experiencias")
                        .HasForeignKey("FkEmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aviscom.Models.Usuario.UsuarioPessoaFisica", "Usuario")
                        .WithMany("Experiencias")
                        .HasForeignKey("FkUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Aviscom.Models.Usuario.UsuarioFuncao", b =>
                {
                    b.HasOne("Aviscom.Models.Usuario.Funcao", "Funcao")
                        .WithMany("UsuarioFuncoes")
                        .HasForeignKey("FkFuncaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aviscom.Models.Usuario.UsuarioPessoaFisica", "UsuarioFisica")
                        .WithMany("UsuariosFuncoes")
                        .HasForeignKey("FkPessoaFisicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aviscom.Models.Usuario.UsuarioPessoaJuridica", "UsuarioJuridica")
                        .WithMany("UsuariosFuncoes")
                        .HasForeignKey("FkPessoaJuridicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aviscom.Models.Usuario.Setor", "Setor")
                        .WithMany("UsuarioFuncoes")
                        .HasForeignKey("FkSetorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcao");

                    b.Navigation("Setor");

                    b.Navigation("UsuarioFisica");

                    b.Navigation("UsuarioJuridica");
                });

            modelBuilder.Entity("Aviscom.Models.Usuario.UsuarioPessoaJuridica", b =>
                {
                    b.HasOne("Aviscom.Models.Usuario.UsuarioPessoaFisica", "Responsavel")
                        .WithMany("EmpresasResponsavel")
                        .HasForeignKey("FkResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("Aviscom.Models.Usuario.Empresa", b =>
                {
                    b.Navigation("Experiencias");
                });

            modelBuilder.Entity("Aviscom.Models.Usuario.Funcao", b =>
                {
                    b.Navigation("UsuarioFuncoes");
                });

            modelBuilder.Entity("Aviscom.Models.Usuario.Instituicao", b =>
                {
                    b.Navigation("EscolaridadesAssociadas");
                });

            modelBuilder.Entity("Aviscom.Models.Usuario.Setor", b =>
                {
                    b.Navigation("UsuarioFuncoes");
                });

            modelBuilder.Entity("Aviscom.Models.Usuario.UsuarioPessoaFisica", b =>
                {
                    b.Navigation("Contatos");

                    b.Navigation("EmpresasResponsavel");

                    b.Navigation("Enderecos");

                    b.Navigation("Escolaridades");

                    b.Navigation("Experiencias");

                    b.Navigation("UsuariosFuncoes");
                });

            modelBuilder.Entity("Aviscom.Models.Usuario.UsuarioPessoaJuridica", b =>
                {
                    b.Navigation("Contatos");

                    b.Navigation("Enderecos");

                    b.Navigation("UsuariosFuncoes");
                });
#pragma warning restore 612, 618
        }
    }
}
